/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e392325bb8682ca277b4c256bb40396d)
interface __BaseEnv_Env {
	R2: R2Bucket;
	ANALYTICS: AnalyticsEngineDataset;
	PDF_QUEUE: Queue;
	BROWSER: BrowserRun;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	PDF_WORKFLOW: Workflow<Parameters<import("./src/worker").PdfWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
